language: objective-c
osx_image: xcode9
script:
    - xcodebuild clean test -workspace TeamGen.xcworkspace -scheme TeamGenFoundation -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty -c
    - xcodebuild clean test -workspace TeamGen.xcworkspace -scheme TeamGen -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty -c
before_install:
    - brew update
    - brew outdated carthage || brew upgrade carthage
    - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

cache:
    directories:
        - Carthage
